# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f66dae86bf06b8b1f23965ddc9023510889767b4fa418e8be6d0b9284fd6ca4b6a794ab155bd0f10e102e74dd2116227b7bbdd2d63f57e075184a29a26b6f9

test:
  secret_key_base: 59616fe743aff79120d36cc1fa8c5f224e917180cba8ed77dd8bf4648a4cb7a2d205b86cf8e729ef9348429d5f159052ae245ca8ea90636c035a9cdc31b86203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
